package model;

public enum Ville{

	Tunis,
	Sfax,
	Sousse,
	Kairouan,
	Bizerte,
	Gabès,
	La_Soukra,
	Ariana,
	Sidi_Hassine,
	El_Mourouj,
	Gafsa	,
	Raoued	,
	Monastir,
	La_Marsa,
	Ben_Arous,
	Kasserin,
	Douar_Hicher,
	Djerba_Houmt_Souk	,
	Le_Kram	,
	Hammamet,
	Zarzis,
	Le_Bardo	,
	Médenin,
	Nabeul	,
	Tataouine	,	
	Ben_Gardane	,	
	Djerba_Midoun	,	 
	Béja	, 
	Msaken	,	 
	Radès	,	 
	Oued_Ellil	,	 
	Moknine,	 
	Le_Kef	,	 
	Menzel_Bourguiba	,	
	Kalâa_Kebira	,	
	Sakiet_Ezzit	,	
	Mahdia,	 
	Jemmal,	 
	Ksar_Hellal,	 
	Sidi_Bouzid	,	 
	Kélibia	,	 
	Sakiet_Eddaïer	,	 
	La_Goulette	,	 
	Jendouba	,	 
	El_Aïn	,	 
	Hammam_Sousse	,	 
	Hammam_Lif	,	 
	Dar_Chaâbane	,	 
	El_Hamma	,	 
	Gremda	,	 
	Bou_Mhel_el_Bassatine	,	 
	Menzel_Temime	,	 
	Korba	,	 
	Métlaoui	,	 
	Soliman	,	 
	Téboulba,	 
	Tozeur	,	 
	Ezzahra	,	 
	Kalâa_Seghira	,	 
	Mateur	,	 
	El_Ksar	,	 
	Thyna	,	 
	La_Manouba	,	 
	Hammam_Chott	,	 
	Siliana	,	 
	Douz	,	 
	Mornag	,	 
	Fériana	,	 
	Ksour_Essef,	 
	Djedeida	,	 
	Ras_Jebel	,	 
	Ghannouch	,	 
	Tebourba	,	 
	Akouda	,	 
	Mégrine	,	 
	Den_Den	,	 
	Chihia	,	 
	Redeyef	,	 
	Sbeïtla	,	 
	Grombalia	,	 
	Djerba_Ajim	,	 
	El_Fahs	,	 
	Ouled_Chamekh,	 
	Menzel_Jemil	,	 
	Chebba,	 
	Takelsa	,	 
	Ouerdanine,	 
	Nefta	,	 
	Medjez_el_Bab	, 
	Bou_Salem	,	 
	Béni_Khiar	,	 
	Moularès	,	 
	El_Jem,	 
	Tinja	,	 
	Zaghouan	,	 
	Zaouiet_Sousse,	 
	Kébili	,	 
	Mornaguia	,	 
	Tabarka	,	 
	Ghardimaou	,	 
	Menzel_Abderrahmane	,	 
	Sahline_Moôtmar,	 
	Souk_Lahad	,	 
	Menzel_Bouzelfa	,	 
	El_Alia	,	 
	Thala	,	 
	Kalâat_el_Andalous	, 
	Bekalta,	 
	Tajerouine	,	 	 
	Carthage	,	 
	Zéramdine,	 
	Bembla,	 
	Mahrès	,	 
	Kerkennah	,	 
	Béni_Khalled	,	 
	Chenini_Nahal	,	 
	Meknassy	,	 
	Bennane_Bodheur,	 
	El_Guettar	,	 
	Makthar	,	 
	Testour	, 
	Bou_Arada	,	 
	Ksibet_el_Médiouni,	 
	Dahmani	,	 
	Sayada,	 
	Menzel_Hayet,	 
	Messaadine	,	 
	Mdhilla	,	 
	Le_Sers	,	 
	Bou_Argoub	,	 
	Skhira	,	 
	Téboursouk	, 
	Zriba	,	 
	Menzel_Ennour,	 
	Mareth	,	 
	Ksibet_Thrayet	,	 
	Agareb	,	 
	Regueb	,	 
	Sidi_Thabet	, 
	Khniss,	 
	Enfida	,	 
	Rejiche,	 
	Métouia	,	 
	Hajeb_El_Ayoun	,	 
	Gaâfour	,	 
	Sidi_Bou_Ali	,	 
	Oudhref	,	 
	Bouficha	,	 
	Metline	,	 
	Raf_Raf	,	 
	Jérissa	,	 
	Aïn_Draham	,	 
	Ghomrassen	,	 
	Sened	,	 
	El_Haouaria	,	 
	Tazarka	,	 
	Sidi_Ali_Ben_Aoun	,	 
	Hammam_Ghezèze	,	 
	Oueslatia	,	 
	Beni_Hassen,	 
	Khalidia	,	 
	Menzel_Kamel,	 
	Haffouz	,	 
	Sidi_Ameur,	 
	Bir_Mcherga	,	 
	Kalaat_Senan	,	 
	Amiret_Hajjaj,	 
	El_Maâmoura	,	 
	Sbikha	,	 
	Bir_Lahmar	,	 
	El_Golâa	,	 
	Degache	,	 
	Zaouiet_Djedidi	,	 
	El_Krib	,	 
	Bou_Hajla	,	 
	El_Maâgoula	, 
	Foussana	,	 
	El_Hencha	,	 
	Nadhour	,	 
	Nouvelle_Matmata,	 
	Sidi_Alouane,	 
	Kerker,	 
	Hergla	,	 
	El_Bradâa,	 
	Mezzouna	,	 
	Nefza	, 
	Touza,	 
	Jemna	,	 
	Jebiniana	,	 
	Menzel_Bouzaiane	,	 
	Somâa	,	 
	Thélepte	,	 
	Zaouiet_Kontoch,	 
	Melloulèche,	 
	Borj_El_Amri	,	 
	Sbiba	,	 
	Bir_El_Hafey	,	 
	Majel_Bel_Abbès	,	 
	El_Batan	,	 
	El_Hamma_du_Jérid	,	 
	Sakiet_Sidi_Youssef	,	 
	Remada	,	 
	Amiret_Touazra,	 
	Bouhjar,	 
	Sidi_Bou_Saïd	,	 
	El_Ksour	,	 
	Jilma	,	 
	Lamta,	 
	Chorbane,	 
	Sejnane	,	 
	Zarat	,	 
	Essouassi,	 
	Ghar_El_Melh	,	 
	Djebel_Oust	,	 
	Amiret_El_Fhoul,	 
	Menzel_Horr	,	 
	Amdoun	, 
	Aousja	,	 
	El_Ghnada,	 
	Azmour	,	 
	Nasrallah	,	 
	Bargou	,	 
	Bir_Ali_Ben_Khalifa	,	 
	El_Masdour,	 
	Rouhia	,	 
	Dar_Allouch	,	 
	Sidi_Bennour,	 
	Cherahil,	 
	Jedelienne	,	 
	Bou_Merdes,	 
	Dehiba	,	 
	El_Mida	,	 
	Goubellat	, 
	Menzel_Mehiri	,	 
	Fernana	,	 
	Kondar	,	 
	Menzel_Fersi,	 
	Korbous	,	 
	Haïdra	,	 
	Cebbala_Ouled_Asker	,	 
	Nebeur	,	 
	El_Alâa	,	 
	Sidi_Bou_Rouis	,	 
	Graïba	,	 
	Hebira,	 
	Sidi_Makhlouf	,	 
	Beni_Khedache	,	 
	Chebika	,	 
	El_Aroussa	,	 
	Sidi_El_Hani	,	 
	Kesra	,	 
	Kalâat_Khasba	,	 
	Ouchtata	,
	Slouguia	,
	Sidi_Ismail	,
	Ouled_Haffouz	,	 
	Oued_Meliz	,	 
	Tamerza	,	 
	Menzel_Chaker	,	 
	Touiref	,	 
	Matmata	,	 
	Menzel_Salem	,	 
	Aïn_Djeloula	,	 
	Echrarda	,	 
	Beni_MTir	,	
	 Aachech	,	 
	 Al_Ahouaz_El_Assouda	,	 
	 Belkhir	,	 
	 Bouchemma	,	 
	 El_Amra	,	 
	 El_Ayoun	,	 
	 Ennasr	,	 
	 Ezzouhour	,	 
	 Essaïda	,	 
	 Faouar	,	 
	 Fouchana	,	 
	 Ghezala	,	 
	 Hadjeb	,	 
	 Hassi_El_Ferid	,	 
	 Hazeg_Ellouza	,	 
	 Hazoua	,	 
	 Hkaima,	 
	 Joumine	,	 
	 Lela	,	 
	 Menzel_El_Habib	,	 
	 Mohamedia	,	 
	 Mnihla	, 
	 Nadhour_Sidi_Ali_Ben_Abed	,	 
	 Ouabed_Khazanet	,	 
	 Rjim_Maatoug	,	 
	 Saouaf	,	 
	 Sidi_Aïch	,	 
	 Sidi_Zid,	 
	 Smar,	 
	 Souk_Jedid	,	 
	 Teboulbou	,	 
	 Thibar	, 
	 Tlelsa,	 
	 Utique	,	 
	 Zarzis_Nord	,	 
	 Zelba
}
